export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={`flex items-center h-full justify-center`}>{children}</div>
  );
}
